blueprint:
  name: Doorsensor Pushover notification
  description: Send a pushover notification after timeX when door opens and send again notification after time X when door closed  
  domain: automation
  input:
    binaryDoor_sensor:
      name: Doorn sensor
      description: This sensor will be used to identify if door is opened or closed
      selector:
        entity:
          domain: binary_sensor
          device_class: opening
    openedSinceMinutes:
      name: Notify after Minutes
      description: Notify when door is opened for X-Minutes
      default: 1
      selector:
        number: 
          min: 1
          max: 10
          step: 1
          unit_of_measurement: minutes
    closeConfirmSeconds:
      name: Close notification after Seconds
      description: Notify when door is back again closed after X-Seconds
      default: 10
      selector: 
        number:
          min: 5
          max: 50
          step: 5
          unit_of_measurement: seconds
    sendOnDoorOpenedVeryLongHours:
      name: Door closed very long duration in hours
      description: Notify when e.g. Homeassistant is restarted and process was interrupted. Send notification if we found very long OPEN door.
      default: 1
      selector: 
        number:
          min: 1
          max: 10
          step: 1
          unit_of_measurement: hours
    messageOpened:
      name: Message sent when door is opened longer
      description: This message is sent when door is opened for a longer time
      default: Door is opened since x minutes!
      selector:
        text: 
    messageClosed:
      name: Message sent when door is closed back again
      description: This message is sent when door closed after it was opened before
      default: Door is closed back again.
      selector:
        text: 
trigger:
  - platform: state
    entity_id: !input binaryDoor_sensor
    for: !input openedSinceMinutes
    from: "off"
    to: "on"
  - type: opened
    platform: device
    device_id: !input binaryDoor_sensor
    entity_id: !input binaryDoor_sensor
    domain: binary_sensor
    for: !input sendOnDoorOpenedVeryLongHours
condition: []
action:
  - if:
      - type: is_open
        condition: device
        device_id: !input binaryDoor_sensor
        entity_id: !input binaryDoor_sensor
        domain: binary_sensor
    then:
      - service: notify.pushover
        data:
          message: !input messageOpened
    else: []
  - repeat:
      until:
        - type: is_not_open
          condition: device
          device_id: !input binaryDoor_sensor
          entity_id: !input binaryDoor_sensor
          domain: binary_sensor
          for: !input closeConfirmSeconds
      sequence:
        - delay: !input closeConfirmSeconds
  - service: notify.pushover
    data:
      message: !input messageClosed
mode: single
